### ISSUE TITLE
Fatal Error in whatsprot class

### ISSUE THREAD

**Issue by Pigrecolab** [WHAnonymous/Chat-API#1026]
Hello,
I have the following error on opening the class

`Fatal error: Call to undefined function openssl_random_pseudo_bytes() in C:\_Lavori in corso\whatsapp-api\Chat-API-master\Chat-API-master\src\whatsprot.class.php on line 2281`

I tried a simple script (I obfuscate my number) :

```php
  $username="39338XXXXXXX";
  $type="sms";
  $nickname = 'John Doe';

  if (!preg_match('!^\d+$!', $username))
  {
    echo "Wrong number. Do NOT use '+' or '00' before your number\n";
    exit(0);
  }

  $debug = true;

  require_once('../src/whatsprot.class.php');
    // Create a instance of WhastPort.
  $w = new WhatsProt($username, '', $debug);
```

**Comment by Pigrecolab** [comment]
Sorry,
it was a php.ini misconfiguration...
 I solved it by editing my php.ini file - changing ;extension=php_openssl.dll to extension=php_openssl.dll .

**Comment by mgp25** [comment]
@Pigrecolab Why you do this? For God’s sake, read the wiki! ==> [Wiki](https://github.com/WHAnonymous/Chat-API/wiki/WhatsAPI-Documentation#dependencies)

Have you read it? I think not, because there is a section called `Dependencies` where its written what you need to install to make the API work.

Also, i think you haven't read this issue #556, in that issue there is a link to a guide on how to quote correctly your code (as i did right now with yours).

And your code should be this btw:

```php
  require_once('../src/whatsprot.class.php');
  $username="39338XXXXXXX";
  $nickname = 'John Doe';

  if (!preg_match('!^\d+$!', $username))
  {
    echo "Wrong number. Do NOT use '+' or '00' before your number\n";
    exit(0);
  }

  $debug = true;
    // Create a instance of WhastPort.
  $w = new WhatsProt($username, '', $debug);
```
