### ISSUE TITLE
SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

### ISSUE THREAD

**Issue by weerdm** [WHAnonymous/Chat-API#1162]
Hi,

First of all thumbs-up you for your great work!

I just updated to version `v2.5.5.3` to enable e2e-encryption; running on SSL and PHP5.6. The problem occurs when sending media or basically when trying to open secure sockets. In this [thread](https://github.com/WHAnonymous/Chat-API/issues/781#issuecomment-109886033) someone posted a fix, but off-course I rather do not want to edit code from a vendor.

Any tips?

Thanks!

**Comment by mgp25** [comment]
It's a pretty common problem in Windows. You need just to set cacert.pem to curl.cainfo.

Since PHP 5.3.7 you could do:

    download http://curl.haxx.se/ca/cacert.pem and save it somewhere.
    update php.ini -- add curl.cainfo = "PATH_TO/cacert.pem"

Otherwise you will need to do the following for every cURL resource:

curl_setopt ($ch, CURLOPT_CAINFO, "PATH_TO/cacert.pem");

from: https://stackoverflow.com/questions/6400300/https-and-ssl3-get-server-certificatecertificate-verify-failed-ca-is-ok

Regards
