### ISSUE TITLE
onMessage comes encrypted , some comes ok plain text

### ISSUE THREAD

**Issue by yanelev** [WHAnonymous/Chat-API#1332]
```xml
rx  <message from="316654755403@s.whatsapp.net" type="text" id="F20E76232D044C4CA56" offline="3" t="1451372302" notify="????">
rx    <enc v="1" type="pkmsg">3!¦=¦¦FX¦I¦aG¦¦¦,¦¦¦¦¦tV¦¦¦?8!¦U0¦¦¦¦¦:¦:s¦¦h^V¦9?¦¦9¦~"B3
!¦¦t?¦Y¦¦P¦¦V¦¦¦?Dh¦¦¦¦¦]"¦¦~S=¦t
3faV¦¦¦/:p#(¦¦¦¦0¦¦</enc>
rx  </message>
```

Log is attached

**Comment by KapteinBabbalas** [comment]
I have the same issue on the .Net API and reported it, but I was told my mp25 to f**k off and use the php library if I want to read encrypted messages. I'm surprised to see the issue is also on the PHP lib. It only started doing this last night.

**Comment by mgp25** [comment]
@yanelev next time, quote debug log properly. Have you read the wiki? You need to install 2 extensions in order to make work the E2E encryption and decrypt messages.

Everything is explained in the wiki and other issues.

@KapteinBabbalas read the wiki and install the extensions, if you dont read you wont learn, once you install the extensions it will work.
