### ISSUE TITLE
Get profile picture is not working its return null value

### ISSUE THREAD

**Issue by gaurav-stepin** [WHAnonymous/Chat-API#1382]
Please quick help for get profile picture in latest whatsapp set. 

require '../src/whatsprot.class.php';

$username = "***********";
$password = "*****************";
$nickname = "********";
$debug = true;
$destinationPhone = '********';

$w = new WhatsProt($username, $nickname, $debug);

$w->Connect();
$w->eventManager()->bind("onGetProfilePicture", "onGetProfilePicture");
$w->LoginWithPassword($password);
$aResponse = $w->sendGetProfilePicture($destinationPhone);
//var_dump($aResponse);

**Comment by marcelvandeweerd** [comment]
Read the wiki. `sendGetProfilePicture` is not returning a profile picture. It only asks the WhatsApp-servers for the profile picture. When the server responds, the method `onGetProfilePicture` is called (because you registered the event). You have to create this method, you can use the example code from the Wiki:

```php
public function onGetProfilePicture( $mynumber, $from, $type, $data )
{
    if ($type == "preview") {
        $filename = "preview_" . $from . ".jpg";
    } else {
        $filename = $from . ".jpg";
    }
    $filename = "ANY FOLDER"."/" . $filename;

    $fp = @fopen($filename, "w");
    if ($fp) {
        fwrite($fp, $data);
        fclose($fp);

    }

    echo '<a href="'.$filename.'"><center><img src="'.$filename.'" height="250" width="250"></center></a><br><br>';

}
```

**Comment by Lorempn2** [comment]
Read the wiki. `sendGetProfilePicture` is not returning the profile picture. It only asks the WhatsApp-servers for the profile-picture. Since you have registered the event `onGetProfilePicture`, you have to create this method to receive the profile-picture. You can use the example code from the wiki:

```php
public function onGetProfilePicture( $mynumber, $from, $type, $data )
{
    if ($type == "preview") {
        $filename = "preview_" . $from . ".jpg";
    } else {
        $filename = $from . ".jpg";
    }
    $filename = "ANY FOLDER"."/" . $filename;

    $fp = @fopen($filename, "w");
    if ($fp) {
        fwrite($fp, $data);
        fclose($fp);

    }

    echo '<a href="'.$filename.'"><center><img src="'.$filename.'" height="250" width="250"></center></a><br><br>';

}
```

**Comment by gaurav-stepin** [comment]
Ok Thx for your replay Mate

**Comment by gaurav-stepin** [comment]
1) I have use whatsapp wiki example 
examples/exampleFunctional.php , i got the image but my profile picture is corrupt 
![919099150010 s whatsapp net](https://cloud.githubusercontent.com/assets/13703116/12108966/1d3d2bbe-b3a3-11e5-96c0-f9050ef37d42.jpg)
Can you have idea anything i am doing wrong ?

Please suggest me quick in Thx in advance.

2) Could we get the whatsapp profile name ?
