### ISSUE TITLE
Sync and Presence on subsequent logins

### ISSUE THREAD

**Issue by CanGokdere** [WHAnonymous/Chat-API#1392]
Firstly I would like to thank you devs for this awesome API.
Now I have some questions which I could not find answers in neither wiki nor past issues

1. I am developing a bot for my whatsapp account. I am using the workflow in wiki, the problem is that each time I kill the script and start again (after I fix a code, add something etc.) previous presenceSubscriptions will not work and I have to subscribe to all of them to work again. So in each login I am sending subscriptions for many contacts without even unsubscribing from them. In wiki it says on other logins we dont need to do sync or presence subscription. Is this intented or am I doing something wrong ?
2. While the bot is running, I would like to get notified by a new contact, not on my contact list. I have no intention of sending message. Do I have to sync before subscribing to presence updates ? (I understand for inital login we MUST sync then sub but what if it is new contact? Wiki always refer this case like sync before sending a message) And also what happens if we sub without sync ?

Thank you

**Comment by mahmoud0m0** [comment]
hey can you check your email please i want to ask you something

**Comment by mgp25** [comment]
1. If you don't receive anything from contacts, you can subcribe to the contacts again, there is no problem in that.

2. If you are starting the conversation, a sync is required, otherwise, if the other user has started the conversation, you don't need to sync it.

Sync = add number to address book.

So answering to your question: If the other has started the conversation you can or not sync it. And if you pretend to add it (save it into your address book, then sync it). 

Q: And also what happens if we sub without sync ?

A: I don't know, but i guess it works perfectly.


Regards
