### ISSUE TITLE
Encrypted messages - Protobuf and curve25519 issues

### ISSUE THREAD

**Issue by fbalaguera** [WHAnonymous/Chat-API#1405]
When I check the extension with extension_loaded(), protobuf passed but curve25519 fail, when I verify with php -m both are available. What Web server is the best?, I'm using the Ubuntu Server 14.04 LTS. Thanks.

**Comment by JohnJexon** [comment]
Working like a charm here. I'm using centos/apache/php56w
https://webtatic.com/packages/php56/

**Comment by rogobob** [comment]
@fbalaguera Did you load the extensions in the php.ini via "extension=..."? Are you 100% sure you are using the correct php.ini file? Did you compile the extensions as mentioned in their readme's? PHP >=5.6 is required by the way.

I had an issue where if I test with php -m I get different results than if I test via code hosted on a web server because the web server was using a different php.ini file that was not configured correctly.

**Comment by fbalaguera** [comment]
Yes, I'm installed, the protobuf is ok, but curve fail, when I put if(extension_loaded(curve...)) this goto else sentense. Thanks.

**Comment by rogobob** [comment]
@fbalaguera If an extension is not loaded this is a problem with your environment / setup and not this code. Double check and redo your setup. It works with me.
