### ISSUE TITLE
Syntax

### ISSUE THREAD

**Issue by ducch** [WHAnonymous/Chat-API#1413]
Can we consider changing the code syntax to be more readable, less junky, etc.? The current code has different pieces of it in different styles.
I propose a 2 spaces tabbing. Class and functions will have { } on new lines, while ifs, whiles, etc. will have it in line. One-liners won't have { }.

I propose something like that:
```
class X
{
  public $var = true;

  function __construct()
  {
    if ($condition) {
      echo "hello";
      echo "world";
    } else {
      echo "hello";
      echo "world";
    }

    if ($something)
      do_something();
    else
      something_else();
  }
}      
```

I can spend some time harmonizing this, but I probably won't be able to do it _all_ on my own.

**Comment by david-perez** [comment]
Yeah, the code style is a mess. It's time someone makes the code [PSR-2 compliant](http://www.php-fig.org/psr/psr-2/). Instead of rewriting it I suggest using an automated tool (IDEs have pretty decent ones), plus, maybe a repo owner can check out and integrate [Style CI](https://styleci.io/), given that this is a public repo and it'd be free of charge.

**Comment by JohnJexon** [comment]
Off topic. Not related to API issue.

**Comment by mgp25** [comment]
Already merged changes using Style CI

Regards
