### ISSUE TITLE
Get messages received Offline

### ISSUE THREAD

**Issue by chcibelli** [WHAnonymous/Chat-API#793]
Hi,

I created and script that runs from command line and "listen" for new messages every time. The problem is that sometimes Whatsapp get disconnected. I fix this "reloading" the script with a cron job each 10 minutes

But maybe while its relaunching a messages arrives and i cant get this

There's any method to get messages received offline?

Thanks,

**Comment by ducch** [comment]
This doesn't make much sense. A message is (at least theoretically) removed from whatsapp's servers when it's [pulled from the server](https://github.com/WHAnonymous/Chat-API/blob/master/src/whatsprot.class.php#L552), or when it's been lying there for too long (IIRC a matter of weeks, not minutes).
If you script crashed somehow, it obviously did not pull the newer messages, and since you restart it within minutes, the time frame after which whatsapp deletes the messages from its servers, has obviously did not passed.
You should be pulling the newer messages that you missed after your next sign-on - they should be there and you should get them.

**Comment by WHAnonymous** [comment]
As @ducch has said, if you dont received the message, you can receive it in the next login, if you have receive it, it wont be received again as its being removed from the server
