### ISSUE TITLE
presence deny blockes the my account

### ISSUE THREAD

**Issue by yanelev** [WHAnonymous/Chat-API#800]
Hi,

Today my number was blocked, I saw that I get the below error.
```xml
rx <presence from="316xxxxxxxx@s.whatsapp.net" type="unavailable" last="deny"></presence>
```
This message is received from the other side into my number. I noticed that the user has privacy settings disabing the "last seen". 
Not sure what is going on...

Is there a way not to get/send presence to accounts with presence disabled?
Is there a solution for such problem?

Thanks

**Comment by WHAnonymous** [comment]
@yanelev that is ok, WhatsApp application does the same, if the user has privacy settings enabled it's normal that you are receiving that node, and as that isn't a problem then you need nothing.

As mentioned above, its fine to receive that node. If you are blocked it's because of sending massive requests.
