### ISSUE TITLE
loginWithPassword Tree length did not match received length

### ISSUE THREAD

**Issue by kharchenkodenis** [WHAnonymous/Chat-API#829]
```
Fatal error: Uncaught exception 'ConnectionException' with message 'Tree length did not match received length (buff = 20 & treeLength = 25)' in whatsprot.class.php:3342 
```

how it fix?

**Comment by mgp25** [comment]
@kharchenkodenis show debug log and what were you trying + if this account was registered using this API.

**Comment by kharchenkodenis** [comment]
after downgrading to php 5.3 appeared a new error

**Comment by mgp25** [comment]
@kharchenkodenis Try `blockChecker.php` from [here](https://github.com/WHAnonymous/Chat-API/blob/master/examples/blockChecker.php) and try if your account is not blocked.

**Comment by kharchenkodenis** [comment]
o my god
```
#################### # # # WA Block Checker # # # #################### Username (country code + number without + or 00): Your number 79859166866 with the following password +UV+7+OnpKTiuVsiYxWOuibMGV4= is not blocked
```

it was trying to send message without sync ((

**Comment by mgp25** [comment]
@kharchenkodenis i recommend you, registering again your number using `registerTool.php` and your problem will be solved.

And if you have any other question, just let me know

Regards

**Comment by murderer99** [comment]
Good day!
I'v encountered this problem. Password was getted with registerTool.php, but:
Fatal error: Uncaught exception 'ConnectionException' with message 'Tree length did not match received length (buff = 21 & treeLength = 25)'

Stack trace: 
#0 ../whatsprot.class.php(301): WhatsProt->readStanza() 
#1 ../Login.php(42): WhatsProt->pollMessage() 
#2 ../whatsprot.class.php(279): Login->doLogin() 
#3 ../index.php(77): WhatsProt->loginWithPassword('Zjzhvc3qiy2KNts...') 
#4 {main} thrown in ../whatsprot.class.php on line 2538

i guess this is due to incorrect php extensions version or php settings (sockets?), becouse i was tested previous version of your lib on may-june 2015, this was works on some servers, and works not on others servers. The error was the same - "Fatal error: Uncaught exception 'ConnectionException' with message 'Tree length did not match received length..."

Now this error permanently occurs on all testing servers.

Could you send me your phpinfo()? my config attached.
[phpinfo.pdf](https://github.com/WHAnonymous/Chat-API/files/42451/phpinfo.pdf)
