### ISSUE TITLE
Error: no_routes in all numbers

### ISSUE THREAD

**Issue by edgar017** [WHAnonymous/Chat-API#895]
```
Array ( 
[in] => XXXXXXXXXX 
[cc] => 52 
[id] => •¬¼oñóÚõÖye-³-»xÏ 
[lg] => es 
[lc] => MX 
[sim_mcc] => 334 
[sim_mnc] => 000 
[method] => sms
[token] => 3628263282eb9d080d286209da7722ef ) 

stdClass Object ( 
[status] => fail 
[reason] => no_routes 
[retry_after] => 3600 ) 
```

In all numbers you have entered this error mark me, I even bought a new number and I mark this error, which could be the solution?

**Comment by mgp25** [comment]
@edgar017 check adding this as country code `521` instead of `52`.

Also, note that some virtual providers are blocked and show `no_routes` as an error. 

https://github.com/WHAnonymous/Chat-API/wiki/Frequently-asked-questions#registration-no_routes-and-bad_param-issue

try with the `521`, if that doesn't work you can try other network options, is explained here: https://github.com/WHAnonymous/Chat-API/wiki/WhatsAPI-Documentation#number-registration

Regards
